[build]
  command = ""
  publish = "."

[build.functions]
  directory = "netlify/functions"

[dev]
  command = "npx serve ."
  port = 8000
  targetPort = 8000

[[redirects]]
  from = "/.netlify/functions/*"
  to = "/.netlify/functions/:splat"
  status = 200
